#!/usr/bin/with-contenv bash

CWD=${PWD};

apache_config() {
    mkdir -p \
        /config/www \
        /config/etc/apache2 \
        /config/log/apache2 \
        /config/keys \
        /run \
        /var/tmp/apache2 \
        /run/apache2
    if [[ ! -h /var/www/html ]]; then
        echo "**** (apache_config) Binding html dir ****";
        rm -rf /var/www/html;
        ln -s /config/www/ /var/www/html;
    fi
    if [[ ! -f /config/etc/apache2/apache2.conf ]]; then
        echo "**** (apache_config) Setting up initial apache2 configs ****";
        mkdir -p \
            /config/etc/apache2 \
            /config/etc/apache2/sites-available \
            /config/etc/apache2/sites-enabled;
        if [[ ! -h /etc/apache2 ]]; then
            cp -rf /etc/apache2/* /config/etc/apache2/;
        fi
        cp -rf /defaults/etc/apache2/* /config/etc/apache2/;
        rm -rf /config/etc/apache2/sites-available/*;
        rm -rf /config/etc/apache2/sites-enabled/*;
        cp -f /defaults/default.conf /config/etc/apache2/sites-available/default.conf;
        cd /config/etc/apache2/sites-enabled/;
        ln -s ../sites-available/default.conf default.conf;
        cd ${CWD};
    fi
    if [[ ! -h /etc/apache2 ]]; then
        echo "**** (apache_config) Binding apache2 config folder ****";
        rm -rf /etc/apache2;
        ln -s /config/etc/apache2 /etc/apache2;
    fi
    if [[ $(find /config/www -type f | wc -l) -eq 0 ]]; then
        echo "**** (apache_config) Install default index page ****";
        cp /defaults/index.html /config/www/index.html;
    fi
    if [[ -f /var/run/apache2/apache2.pid ]]; then
        rm -f /var/run/apache2/apache2.pid
    fi
    chown -R $PUID:$PGID \
        /run/apache2 \
        /var/lib/apache2
    chmod -R g+w \
        /config/www
}
permissions_config() {
    echo "**** (permissions_config) Settings permissions ****";
    mkdir -p \
        /config/keys \
        /config/log \
        /config/tmp \
        /run \
        /tmp
    chown -R $PUID:$PGID \
        /config \
        /config/keys
    chmod -R a+w \
        /tmp \
        /config/log
}

permissions_config;
apache_config;
permissions_config;